last : testM.o
	LD_LIBRARY_PATH=/home/maheshlinux/unix-/mainShar:$LD_LIBRARY_PATH
testM.o: init.c /home/maheshlinux/unix-/mainShar/libmy.so
	 gcc -I /home/maheshlinux/unix-/mainShar -L /home/maheshlinux/unix-/mainShar -o testM init.c -lmy
