main : mainUser.o
	gcc -o main mainUser.o -L/home/maheshlinux/unix-/StaticLib/ArrayPro/ -lmy 
#libmy.a : /home/maheshlinux/unix-/StaticLib/ArrayPro/ArrayLib.o
#	ar rcs libmy.a /home/maheshlinux/unix-/StaticLib/ArrayPro/ArrayLib.o
mainUser.o : mainUser.c
	gcc -c mainUser.c
